//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESSE
    {
        public ADRESSE()
        {
            this.LIVRAISON = new HashSet<LIVRAISON>();
        }
    
        public int NumAdresse { get; set; }
        public string Adresse1 { get; set; }
        public int NumQuartier { get; set; }
    
        public virtual QUARTIER QUARTIER { get; set; }
        public virtual ICollection<LIVRAISON> LIVRAISON { get; set; }
    }
}
