//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class BON_LIV
    {
        public BON_LIV()
        {
            this.FACTURE_CLIENT = new HashSet<FACTURE_CLIENT>();
            this.LIVRAISON = new HashSet<LIVRAISON>();
        }
    
        public int NumBonLiv { get; set; }
        public int NumCdeClient { get; set; }
        public System.DateTime DateLiv { get; set; }
    
        public virtual CDE_CLIENT CDE_CLIENT { get; set; }
        public virtual ICollection<FACTURE_CLIENT> FACTURE_CLIENT { get; set; }
        public virtual ICollection<LIVRAISON> LIVRAISON { get; set; }
    }
}
