//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class CataloguePizza
    {
        public CataloguePizza()
        {
            this.FABRICATION = new HashSet<FABRICATION>();
            this.FABRICATION1 = new HashSet<FABRICATION>();
            this.LIGNES_CDE_CLIENT = new HashSet<LIGNES_CDE_CLIENT>();
            this.LIGNES_CDE_CLIENT1 = new HashSet<LIGNES_CDE_CLIENT>();
        }
    
        public int NumPizza { get; set; }
        public string NomPizza { get; set; }
        public string TaillePizza { get; set; }
        public double PrixPizza { get; set; }
    
        public virtual ICollection<FABRICATION> FABRICATION { get; set; }
        public virtual ICollection<FABRICATION> FABRICATION1 { get; set; }
        public virtual ICollection<LIGNES_CDE_CLIENT> LIGNES_CDE_CLIENT { get; set; }
        public virtual ICollection<LIGNES_CDE_CLIENT> LIGNES_CDE_CLIENT1 { get; set; }
    }
}
