//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDE_CLIENT
    {
        public CDE_CLIENT()
        {
            this.BON_LIV = new HashSet<BON_LIV>();
            this.LIGNES_CDE_CLIENT = new HashSet<LIGNES_CDE_CLIENT>();
        }
    
        public int NumCdeClient { get; set; }
        public bool LivreEmporte { get; set; }
        public System.DateTime DateCde { get; set; }
        public int NumClient { get; set; }
    
        public virtual ICollection<BON_LIV> BON_LIV { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual ICollection<LIGNES_CDE_CLIENT> LIGNES_CDE_CLIENT { get; set; }
    }
}
