//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.CDE_CLIENT = new HashSet<CDE_CLIENT>();
            this.CDE_CLIENT1 = new HashSet<CDE_CLIENT>();
        }
    
        public int NumClient { get; set; }
        public string NomClient { get; set; }
        public string PrenomClient { get; set; }
        public string Adresse { get; set; }
    
        public virtual ICollection<CDE_CLIENT> CDE_CLIENT { get; set; }
        public virtual ICollection<CDE_CLIENT> CDE_CLIENT1 { get; set; }
    }
}
