//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class FABRICATION
    {
        public int NumFab { get; set; }
        public int QteFab { get; set; }
        public System.DateTime DateFab { get; set; }
        public int NumPizza { get; set; }
    
        public virtual CataloguePizza CataloguePizza { get; set; }
        public virtual CataloguePizza CataloguePizza1 { get; set; }
    }
}
