//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURE_CLIENT
    {
        public FACTURE_CLIENT()
        {
            this.PAIEMENT_FACT = new HashSet<PAIEMENT_FACT>();
            this.PAIEMENT_FACT1 = new HashSet<PAIEMENT_FACT>();
        }
    
        public int NumFacture { get; set; }
        public int NumBonLiv { get; set; }
        public System.DateTime DateFacture { get; set; }
        public double MontantTotal { get; set; }
    
        public virtual BON_LIV BON_LIV { get; set; }
        public virtual BON_LIV BON_LIV1 { get; set; }
        public virtual ICollection<PAIEMENT_FACT> PAIEMENT_FACT { get; set; }
        public virtual ICollection<PAIEMENT_FACT> PAIEMENT_FACT1 { get; set; }
    }
}
