//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADRESSE> ADRESSE { get; set; }
        public DbSet<BON_LIV> BON_LIV { get; set; }
        public DbSet<CataloguePizza> CataloguePizza { get; set; }
        public DbSet<CDE_CLIENT> CDE_CLIENT { get; set; }
        public DbSet<CLIENT> CLIENT { get; set; }
        public DbSet<FABRICATION> FABRICATION { get; set; }
        public DbSet<FACTURE_CLIENT> FACTURE_CLIENT { get; set; }
        public DbSet<LIGNES_CDE_CLIENT> LIGNES_CDE_CLIENT { get; set; }
        public DbSet<LIVRAISON> LIVRAISON { get; set; }
        public DbSet<PAIEMENT_FACT> PAIEMENT_FACT { get; set; }
        public DbSet<QUARTIER> QUARTIER { get; set; }
        public DbSet<spt_fallback_db> spt_fallback_db { get; set; }
    
        public virtual int sp_MScleanupmergepublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher");
        }
    
        public virtual int sp_MSrepl_startup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSrepl_startup");
        }
    }
}
