//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzeriaEntities : DbContext
    {
        public PizzeriaEntities()
            : base("name=PizzeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADRESSE> ADRESSE { get; set; }
        public DbSet<BON_LIV> BON_LIV { get; set; }
        public DbSet<CataloguePizza> CataloguePizza { get; set; }
        public DbSet<CDE_CLIENT> CDE_CLIENT { get; set; }
        public DbSet<CLIENT> CLIENT { get; set; }
        public DbSet<FABRICATION> FABRICATION { get; set; }
        public DbSet<FACTURE_CLIENT> FACTURE_CLIENT { get; set; }
        public DbSet<LIGNES_CDE_CLIENT> LIGNES_CDE_CLIENT { get; set; }
        public DbSet<LIVRAISON> LIVRAISON { get; set; }
        public DbSet<LIVREUR> LIVREUR { get; set; }
        public DbSet<PAIEMENT_FACT> PAIEMENT_FACT { get; set; }
        public DbSet<QUARTIER> QUARTIER { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
