//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIEMENT_FACT
    {
        public int NumPieceCompt { get; set; }
        public int NumFacture { get; set; }
    
        public virtual FACTURE_CLIENT FACTURE_CLIENT { get; set; }
    }
}
