//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUARTIER
    {
        public QUARTIER()
        {
            this.ADRESSE = new HashSet<ADRESSE>();
            this.LIVREUR = new HashSet<LIVREUR>();
        }
    
        public int NumQuartier { get; set; }
        public string NomQuartier { get; set; }
    
        public virtual ICollection<ADRESSE> ADRESSE { get; set; }
        public virtual ICollection<LIVREUR> LIVREUR { get; set; }
    }
}
